/**
 * @file Diagram (SmartArt) domain module
 *
 * Exports diagram types and layout engine for DiagramML processing.
 *
 * @see ECMA-376 Part 1, Section 21.4 - DrawingML Diagrams
 */

export type {
  DiagramAdjust,
  DiagramAlgorithm,
  DiagramAlgorithmParam,
  DiagramAlgorithmType,
  DiagramAnimLvlStr,
  DiagramAnimOneStr,
  DiagramArrowheadStyle,
  DiagramAutoTextRotation,
  DiagramAxisType,
  DiagramAxisTypes,
  DiagramBackground,
  DiagramBendPoint,
  DiagramBooleans,
  DiagramBoolOperator,
  DiagramBreakpoint,
  DiagramCategory,
  DiagramCenterShapeMapping,
  DiagramChildAlignment,
  DiagramChildDirection,
  DiagramChildOrderType,
  DiagramChoose,
  DiagramClrAppMethod,
  DiagramColorList,
  DiagramColorsDefinition,
  DiagramColorsDefinitionHeader,
  DiagramColorsDefinitionHeaderList,
  DiagramColorStyleLabel,
  DiagramConnection,
  DiagramConnectorDimension,
  DiagramConnectorPoint,
  DiagramConnectorRouting,
  DiagramConstraint,
  DiagramConstraintRelationship,
  DiagramConstraintType,
  DiagramContinueDirection,
  DiagramCxnType,
  DiagramDataModel,
  DiagramDataModelExtension,
  DiagramDirection,
  DiagramElementType,
  DiagramElementTypes,
  DiagramElse,
  DiagramExtension,
  DiagramFallbackDimension,
  DiagramFlowDirection,
  DiagramForEach,
  DiagramFunctionArgument,
  DiagramFunctionOperator,
  DiagramFunctionType,
  DiagramFunctionValue,
  DiagramGrowDirection,
  DiagramHierBranchStyle,
  DiagramHierarchyAlignment,
  DiagramHorizontalAlignment,
  DiagramHueDir,
  DiagramIf,
  DiagramIndex1,
  DiagramInts,
  DiagramLayoutContent,
  DiagramLayoutDefinition,
  DiagramLayoutDefinitionHeader,
  DiagramLayoutDefinitionHeaderList,
  DiagramLayoutNode,
  DiagramLayoutShape,
  DiagramLayoutShapeType,
  DiagramLinearDirection,
  DiagramModelId,
  DiagramNodeCount,
  DiagramNodeHorizontalAlignment,
  DiagramNodeVerticalAlignment,
  DiagramOffset,
  DiagramOutputShapeType,
  DiagramParameterId,
  DiagramParameterValue,
  DiagramPoint,
  DiagramPrSetCustVal,
  DiagramPresentationOf,
  DiagramPropertySet,
  DiagramPyramidAccentPosition,
  DiagramPyramidAccentTextMargin,
  DiagramResizeHandlesStr,
  DiagramRotationPath,
  DiagramRule,
  DiagramSecondaryChildAlignment,
  DiagramSecondaryLinearDirection,
  DiagramStartingElement,
  DiagramStyleDefinition,
  DiagramStyleDefinitionHeader,
  DiagramStyleDefinitionHeaderList,
  DiagramStyleLabel,
  DiagramTextAlignment,
  DiagramTextAnchorHorizontal,
  DiagramTextAnchorVertical,
  DiagramTextBlockDirection,
  DiagramTextDirection,
  DiagramUnsignedInts,
  DiagramVariable,
  DiagramVariableList,
  DiagramVariableType,
  DiagramVerticalAlignment,
  DiagramWhole,
} from "./types";

// Layout engine exports
export {
  buildDiagramTree,
  calculateMaxDepth,
  countNodes,
  filterNodesByType,
  getAncestors,
  getAncestorsOrSelf,
  getContentNodes,
  getDescendants,
  getDescendantsOrSelf,
  getFollowingSiblings,
  getNodeText,
  getPrecedingSiblings,
  getRoot,
  getSiblings,
  traverseTree,
  type DiagramPointType,
  type DiagramTreeBuildResult,
  type DiagramTreeNode,
} from "./layout-engine/tree-builder";

export {
  createChildContext,
  createDefaultContext,
  createEmptyResult,
  getConstraint,
  getParam,
  getVariable,
  mergeBounds,
  type CreateContextOptions,
  type DiagramVariableValue,
  type LayoutAlgorithmFn,
  type LayoutAlgorithmRegistry,
  type LayoutBounds,
  type LayoutContext,
  type LayoutNode,
  type LayoutResult,
} from "./layout-engine/types";

export {
  processLayoutDefinition,
  type LayoutProcessOptions,
  type LayoutProcessResult,
} from "./layout-engine/layout-processor";

export {
  compositeLayout,
  connectorLayout,
  createAlgorithmRegistry,
  cycleLayout,
  getLayoutAlgorithm,
  hierChildLayout,
  linearLayout,
  pyramidLayout,
  snakeLayout,
  spaceLayout,
  textLayout,
} from "./layout-engine/algorithms";

export {
  applyConstraints,
  applyConstraintsToLayout,
  applyRules,
  createConstraintContext,
  evaluateConstraintOperator,
  getHeightConstraint,
  getNodesForRelationship,
  getSpacingConstraint,
  getWidthConstraint,
  resolveAllConstraints,
  resolveConstraint,
  sortConstraintsByDependency,
  type ConstraintContext,
  type ConstraintResult,
  type ResolvedConstraint,
} from "./layout-engine/constraints";

export {
  createForEachChildContext,
  createForEachContext,
  evaluateFunction,
  evaluateIf,
  evaluateOperator,
  filterNodesByPointType,
  processChoose,
  processForEach,
  selectNodesByAxis,
  type ChooseResult,
  type ForEachContext,
  type ForEachResult,
} from "./layout-engine/iteration";

export {
  calculateColorIndex,
  createEmptyColorContext,
  createStyleContext,
  findColorStyleLabel,
  findStyleLabel,
  resolveFillFromList,
  resolveLineFromList,
  resolveNodeStyle,
  type ResolvedDiagramStyle,
  type StyleResolverContext,
} from "./layout-engine/style-resolver";

export {
  generateDiagramShapes,
  generateShapeSvg,
  shapeToSvgAttributes,
  type ShapeGenerationConfig,
  type ShapeGenerationResult,
} from "./layout-engine/shape-generator";
