/**
 * @file Node type constants for Figma fig format
 */

/** Node type values matching Figma's schema */
export const NODE_TYPE_VALUES = {
  DOCUMENT: 1,
  CANVAS: 2,
  GROUP: 3,
  FRAME: 4,
  BOOLEAN_OPERATION: 5,
  VECTOR: 6,
  STAR: 7,
  LINE: 8,
  ELLIPSE: 9,
  RECTANGLE: 10,
  REGULAR_POLYGON: 11,
  ROUNDED_RECTANGLE: 12,
  TEXT: 13,
  SYMBOL: 15,
  INSTANCE: 16,
  SLICE: 17,
  COMPONENT: 18,
  COMPONENT_SET: 19,
  STICKY: 20,
  CONNECTOR: 21,
  SHAPE_WITH_TEXT: 22,
  CODE_BLOCK: 23,
  STAMP: 24,
  WIDGET: 25,
  EMBED: 26,
  LINK_UNFURL: 27,
  MEDIA: 28,
  SECTION: 29,
  TABLE: 30,
  TABLE_CELL: 31,
} as const;

export type NodeType = keyof typeof NODE_TYPE_VALUES;

/** Shape node type values (subset of NODE_TYPE_VALUES) */
export const SHAPE_NODE_TYPES = {
  BOOLEAN_OPERATION: NODE_TYPE_VALUES.BOOLEAN_OPERATION,
  VECTOR: NODE_TYPE_VALUES.VECTOR,
  STAR: NODE_TYPE_VALUES.STAR,
  LINE: NODE_TYPE_VALUES.LINE,
  ELLIPSE: NODE_TYPE_VALUES.ELLIPSE,
  RECTANGLE: NODE_TYPE_VALUES.RECTANGLE,
  REGULAR_POLYGON: NODE_TYPE_VALUES.REGULAR_POLYGON,
  ROUNDED_RECTANGLE: NODE_TYPE_VALUES.ROUNDED_RECTANGLE,
} as const;

export type ShapeNodeType = keyof typeof SHAPE_NODE_TYPES;
