/**
 * @file Fixture-based tests: parse real XLSX files → CSV via convertXlsxToDsv.
 *
 * These tests load pre-built XLSX fixture files (generated by fixtures/generate.ts),
 * parse them through the XLSX parser, then convert to DSV. This validates that
 * formula cells emit their *calculated* (cached) values, not the formula text.
 *
 * The fixtures contain cells with both `<f>` (formula) and `<v>` (cached value)
 * elements. The converter should always produce the `<v>` value in the CSV output.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { loadZipPackage } from "@aurochs/zip";
import { parseXlsxWorkbook } from "@aurochs-office/xlsx/parser";
import type { XlsxWorkbook } from "@aurochs-office/xlsx/domain/workbook";
import { buildDsv } from "@aurochs/dsv";
import { convertXlsxToDsv } from "./xlsx-to-dsv";

// =============================================================================
// Helpers
// =============================================================================

const FIXTURES_DIR = join(import.meta.dirname, "..", "tmp", "fixtures");

async function loadFixture(name: string): Promise<XlsxWorkbook> {
  const bytes = readFileSync(join(FIXTURES_DIR, `${name}.xlsx`));
  const pkg = await loadZipPackage(bytes);
  return parseXlsxWorkbook(async (path) => pkg.readText(path) ?? undefined);
}

function toCsv(workbook: XlsxWorkbook, sheetIndex?: number): string {
  const result = convertXlsxToDsv(workbook, { sheetIndex });
  return buildDsv(result.data);
}

/**
 * Parse CSV text into a 2D array of values (headers + data).
 * Splits on CRLF and commas. Does NOT handle quoted fields —
 * sufficient for these simple fixture outputs.
 */
function parseCsvGrid(csv: string): string[][] {
  return csv
    .trimEnd()
    .split("\r\n")
    .map((line) => line.split(","));
}

// =============================================================================
// formulas.xlsx
// =============================================================================

describe("formulas.xlsx — formula cells emit cached values", () => {
  // eslint-disable-next-line no-restricted-syntax -- shared fixture across tests
  let wb: XlsxWorkbook;
  // eslint-disable-next-line no-restricted-syntax -- shared fixture across tests
  let grid: string[][];

  beforeAll(async () => {
    wb = await loadFixture("formulas");
    grid = parseCsvGrid(toCsv(wb));
  });

  it("has correct headers", () => {
    expect(grid[0]).toEqual(["label", "a", "b", "result"]);
  });

  it("SUM: 10 + 20 = 30", () => {
    const row = grid[1];
    expect(row[0]).toBe("SUM");
    expect(row[3]).toBe("30");
  });

  it("PRODUCT: 3 * 7 = 21", () => {
    const row = grid[2];
    expect(row[0]).toBe("PRODUCT");
    expect(row[3]).toBe("21");
  });

  it("AVERAGE: (100 + 200) / 2 = 150", () => {
    const row = grid[3];
    expect(row[0]).toBe("AVERAGE");
    expect(row[3]).toBe("150");
  });

  it("CONCAT: string formula result", () => {
    const row = grid[4];
    expect(row[0]).toBe("CONCAT");
    expect(row[3]).toBe("HelloWorld");
  });

  it("BOOLEAN: 10 > 5 = true", () => {
    const row = grid[5];
    expect(row[0]).toBe("BOOLEAN");
    expect(row[3]).toBe("true");
  });

  it("NEGATIVE: -15 + 8 = -7", () => {
    const row = grid[6];
    expect(row[0]).toBe("NEGATIVE");
    expect(row[3]).toBe("-7");
  });

  it("DECIMAL: 1.1 + 2.2 = 3.3", () => {
    const row = grid[7];
    expect(row[0]).toBe("DECIMAL");
    expect(row[3]).toBe("3.3");
  });

  it("ZERO: 100 + (-100) = 0", () => {
    const row = grid[8];
    expect(row[0]).toBe("ZERO");
    expect(row[3]).toBe("0");
  });

  it("LARGE: 999999999 + 1 = 1000000000", () => {
    const row = grid[9];
    expect(row[0]).toBe("LARGE");
    expect(row[3]).toBe("1000000000");
  });

  it("NESTED: (5 + 3) * 5 = 40", () => {
    const row = grid[10];
    expect(row[0]).toBe("NESTED");
    expect(row[3]).toBe("40");
  });

  it("EMPTY_REF: empty + 10 = 10", () => {
    const row = grid[11];
    expect(row[0]).toBe("EMPTY_REF");
    expect(row[3]).toBe("10");
  });
});

// =============================================================================
// date-formulas.xlsx
// =============================================================================

describe("date-formulas.xlsx — date formula cells emit ISO 8601 dates", () => {
  // eslint-disable-next-line no-restricted-syntax -- shared fixture across tests
  let wb: XlsxWorkbook;
  // eslint-disable-next-line no-restricted-syntax -- shared fixture across tests
  let grid: string[][];

  beforeAll(async () => {
    wb = await loadFixture("date-formulas");
    grid = parseCsvGrid(toCsv(wb));
  });

  it("has correct headers", () => {
    expect(grid[0]).toEqual(["label", "date", "result"]);
  });

  it("New Year: date cell shows 2024-01-01, formula copy also shows date", () => {
    expect(grid[1][0]).toBe("New Year");
    expect(grid[1][1]).toBe("2024-01-01");
    // C2 has date format + formula =B2
    expect(grid[1][2]).toBe("2024-01-01");
  });

  it("Mid Year: date cell shows 2024-07-01, difference is plain number", () => {
    expect(grid[2][0]).toBe("Mid Year");
    expect(grid[2][1]).toBe("2024-07-01");
    // C3 is plain number (no date format): days difference
    expect(Number(grid[2][2])).toBe(182);
  });

  it("Date Plus 30: formula =B2+30 shows 2024-01-31 (date formatted)", () => {
    expect(grid[3][0]).toBe("Date Plus 30");
    expect(grid[3][1]).toBe("2024-01-31");
    // C4 is plain number: 30 days offset
    expect(Number(grid[3][2])).toBe(30);
  });
});

// =============================================================================
// multi-sheet.xlsx
// =============================================================================

describe("multi-sheet.xlsx — cross-sheet formula references", () => {
  // eslint-disable-next-line no-restricted-syntax -- shared fixture across tests
  let wb: XlsxWorkbook;

  beforeAll(async () => {
    wb = await loadFixture("multi-sheet");
  });

  it("Sheet1 (Source): raw data", () => {
    const grid = parseCsvGrid(toCsv(wb, 0));
    expect(grid[0]).toEqual(["item", "price"]);
    expect(grid[1]).toEqual(["Apple", "1.5"]);
    expect(grid[2]).toEqual(["Banana", "0.75"]);
    expect(grid[3]).toEqual(["Cherry", "3"]);
  });

  it("Sheet2 (Summary): cross-sheet formulas show cached values", () => {
    const grid = parseCsvGrid(toCsv(wb, 1));
    expect(grid[0]).toEqual(["metric", "value"]);
    expect(grid[1]).toEqual(["Total", "5.25"]);
    expect(grid[2]).toEqual(["Count", "3"]);
    expect(grid[3]).toEqual(["Average", "1.75"]);
  });
});

// =============================================================================
// error-values.xlsx
// =============================================================================

describe("error-values.xlsx — formula error values in CSV", () => {
  // eslint-disable-next-line no-restricted-syntax -- shared fixture across tests
  let wb: XlsxWorkbook;
  // eslint-disable-next-line no-restricted-syntax -- shared fixture across tests
  let grid: string[][];

  beforeAll(async () => {
    wb = await loadFixture("error-values");
    grid = parseCsvGrid(toCsv(wb));
  });

  it("DIV/0 error", () => {
    expect(grid[1][0]).toBe("DIV_ZERO");
    expect(grid[1][1]).toBe("#DIV/0!");
  });

  it("REF error", () => {
    expect(grid[2][0]).toBe("REF_ERROR");
    expect(grid[2][1]).toBe("#REF!");
  });

  it("NAME error", () => {
    expect(grid[3][0]).toBe("NAME_ERROR");
    expect(grid[3][1]).toBe("#NAME?");
  });

  it("VALUE error", () => {
    expect(grid[4][0]).toBe("VALUE_ERROR");
    expect(grid[4][1]).toBe("#VALUE!");
  });
});
